sudo: false

notifications:
  email: false


language: python

python:
  - "3.8"

before_script:
  - source .env
  - pip install -r requirements.txt
  - cd service

script:
  - pytest --cov=readonly_model

after_success:
  - codecov
