version: "3"


services:
  redis:
    image: redis:6-buster
    hostname: $${REDIS_HOST}
    container_name: limon-redis
    env_file: .env
    ports:
      - 8080:6379


  postgresql:
    image: postgres:11-alpine
    hostname: $${POSTGRES_HOST}
    container_name: limon-postgresql
    env_file: .env
    ports:
      - 8081:5432
    volumes:
      - pg-data-limon:/var/lib/postgresql/data


  backend:
    image: limon-backend
    container_name: limon-backend
    build: .
    user: appuser
    env_file: .env
    ports:
      - 8082:8082
    volumes:
      - ./service:/app
      - ./requirements.txt:/app/requitements.txt
    depends_on:
      - redis
      - postgresql
    command: /bin/bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        python3 manage.py runserver 0.0.0.0:8082"



volumes:
  pg-data-limon:
